#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nomod"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6  # Sets the number of items per page for older versions.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Latest"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Authors"
    url = "/authors/"
    weight = 3

  [[menu.main]]
    name = "Resources"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "Resources"
    name = "Videos"
    url = "/videos/"
    weight = 1

  [[menu.main]]
    parent = "Resources"
    name = "Featured"
    url = "/featured/"
    weight = 2

  [[menu.main]]
    parent = "Resources"
    name = "Elements"
    url = "/elements/"
    weight = 3

  [[menu.main]]
    parent = "Resources"
    name = "Topics"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

# Call to action button
[params.cta_button]
  enable = true
  cta_button_link = "/contact/"
  cta_button_text = "Get in touch"


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  logo_dark = ""
  description = "Nomod is a multipurpose Hugo blog theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Hero Settings
[params.hero]
  enable = true
  hero__title = "Stories, Journeys, and Ideas for the Creatively Curious"
  hero__description = "Join us on a journey where every post brings a fresh perspective. This blog is for those who are driven by curiosity and a desire to learn."

[params.hero_authors]
  enable = true
  hero_authors_description = "Meet our talented team"


#-------------------------------
# Blog Section Settings
[params.blog]
  enable = true
  blog_title = "Latest"


#-------------------------------
# Recommended Section Settings
[params.recommended]
  enable = true
  recommended_title = "Recommended"
  recommended_tag = "Lifestyle"


#-------------------------------
# About Section Settings
[params.about]
  enable = true
  about_title = "Hello, I’m Giana"
  about_subtitle = "I’m a thinker and storyteller with a passion for exploring the intersection of creativity and technology"
  about_description = """
  Giana Franci’s mission is rooted in the belief that creativity is a catalyst for connection and change. Through her blog, she seeks to bridge the gap between design, technology, and lifestyle, offering a space where ideas can flourish and innovation can thrive.

  It’s a journey through the thoughts and experiences that shape her world. Giana’s work is driven by a desire to challenge the ordinary and to push the boundaries of what’s possible. She sees every project as an opportunity to learn, grow, and inspire others to do the same. This blog is more than just a collection of posts.
  """
  about_image = "https://placehold.co/1200x800"
  about_image_alt = "Giana Franci"
  about_button_text = "Meet our team"
  about_button_link = "/about/"


#-------------------------------
# Authors Section Settings
[params.authors]
  enable = true
  authors_title = "Top authors"


#-------------------------------
# Newsletter Settings
[params.mailchimp]
  enable = true
  mailchimp_title = "Stay Inspired Weekly. Your Friendly Dose of Tips & Insights!"
  mailchimp_description = "Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox."
  mailchimp_identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text = "Your email address"
  mailchimp_button_text = "Subscribe"


#-------------------------------
# Footer Settings
[params.footer]
  footer_description = "Join us on a journey where every post brings a fresh perspective. This blog is for those who are driven by curiosity and a desire to learn."

# Social Links
[[params.social]]
  icon = "fa-brands fa-facebook-f"
  name = "Facebook"
  link = "https://facebook.com"

[[params.social]]
  icon = "fa-brands fa-x-twitter"
  name = "Twitter"
  link = "https://twitter.com"

[[params.social]]
  icon = "fa-brands fa-tiktok"
  name = "Tiktok"
  link = "https://www.tiktok.com"

[[params.social]]
  icon = "fa-brands fa-instagram"
  name = "Instagram"
  link = "https://instagram.com"

[[params.social]]
  icon = "fa-brands fa-mastodon"
  name = "Mastodon"
  link = "https://mastodon.social"

[[params.social]]
  icon = "fa-brands fa-dribbble"
  name = "Dribbble"
  link = "https://www.dribbble.com"

# Example of adding a new link to the footer section:
# [[params.social]]
#   icon = "fa-brands fa-vimeo"
#   name = "Vimeo"
#   link = "https://vimeo.com"

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
[params.contact]
  form_id = "your@email.com" # Add your form_id
  button_text = "Send now"

  # NOTE
  # Nomod comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = true
  disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false