#-------------------------------
# General Site Settings
baseURL = "https://kcti111.github.io/magazine/"
languageCode = "en-us"
title = "KCTI MAGAZINE"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6  # Sets the number of items per page for older versions.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    # name = "Home"
    # url = "/"
    # weight = 1

  [[menu.main]]
    name = "최신 포스트"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "참여연구진"
    url = "/authors/"
    weight = 3

  [[menu.main]]
    name = "문화기술 리소스"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "문화기술 리소스"
    name = "홍보 영상"
    url = "/videos/"
    weight = 1

  [[menu.main]]
    parent = "문화기술 리소스"
    name = "특집 칼럼"
    url = "/featured/"
    weight = 2

  [[menu.main]]
    # parent = "Resources"
    # name = "Elements"
    # url = "/elements/"
    # weight = 3

  [[menu.main]]
    parent = "문화기술 리소스"
    name = "CT 키워드 "
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "매거진 소개"
    url = "/about/"
    weight = 5

# Call to action button
[params.cta_button]
  enable = true
  cta_button_link = "/magazine/contact"
  cta_button_text = "우리와 연결되기"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo_dark.png"
  description = "KCTI is Good team!"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Hero Settings
[params.hero]
  enable = true
  hero__title = "Let's share future technologies, new cultures, and sensational moments."
  hero__description = "미래과학 기술이 단순한 도구를 넘어 새로운 문화로 인식되고, 사람들의 일상과 감각 속에 스며드는 순간들을 기록합니다. 한국 문화기술 이슈 매거진"

[params.hero_authors]
  enable = true
  hero_authors_description = "문화기술 연구진"


#-------------------------------
# Blog Section Settings
[params.blog]
  enable = true
  blog_title = "최근 문화기술 이슈 브리프"


#-------------------------------
# Recommended Section Settings
[params.recommended]
  enable = true
  recommended_title = "문화기술 주제별"
  recommended_tag = "Lifestyle"


#-------------------------------
# About Section Settings
[params.about]
  enable = true
  about_title = "한국문화기술연구소"
  about_subtitle = "여러분과 함께 문화기술을 알아가는 매거진이 되겠습니다"
  about_description = """
  문화기술 이슈 매거진은 기술을 단순한 도구가 아닌 문화적 경험과 사회적 맥락을 만들어내는 매개체로 바라보는 전문 온라인 매거진입니다.

  인공지능, 디지털 미디어, XR, 데이터 기술 등 동시대 핵심 기술이 예술·디자인·서비스·일상 문화와 어떻게 연결되고 확장되는지를 탐구하며,
  기술 중심 담론을 넘어 사람·경험·의미에 초점을 둡니다.
  
  연구자, 창작자, 실무자의 관점을 아우르는 칼럼과 사례 분석을 통해 문화기술의 현재를 기록하고, 미래의 가능성을 질문하는 문화기술 이슈 매거진은
  기술 변화 속에서 새로운 상상력과 공공적 가치를 모색하는 열린 지식 플랫폼을 지향하고 있습니다.
  """
  about_image = "images/Kcti.jpg"
  about_image_alt = "Korea culture technology institute"
  about_button_text = "한국문화기술연구소 사이트"
  about_button_link = "https://kct.gist.ac.kr/kct/index.do"


#-------------------------------
# Authors Section Settings
[params.authors]
  enable = true
  authors_title = "Popular authors"


#-------------------------------
# New요"
  mailchimp_button_text = "구독"


#-------------------------------
# Footer Settings
[params.footer]
  footer_description = "한국문화기술연구소에서는 기술이 단순한 도구를 넘어 문화로 인식되고, 사람들의 일상과 감각 속에 스며드는 순간들을 기록하고 해석하는 문화기술 이슈 매거진을 발행합니다."

# Social Links
[[params.social]]
  icon = "fa-brands fa-facebook-f"
  name = "Facebook"
  link = "https://facebook.com"

[[params.social]]
  icon = "fa-brands fa-x-twitter"
  name = "Twitter"
  link = "https://twitter.com"

[[params.social]]
  icon = "fa-brands fa-tiktok"
  name = "Tiktok"
  link = "https://www.tiktok.com"

[[params.social]]
  icon = "fa-brands fa-instagram"
  name = "Instagram"
  link = "https://instagram.com"

[[params.social]]
  icon = "fa-brands fa-mastodon"
  name = "Mastodon"
  link = "https://mastodon.social"

[[params.social]]
  icon = "fa-brands fa-dribbble"
  name = "Dribbble"
  link = "https://www.dribbble.com"

# Example of adding a new link to the footer section:
# [[params.social]]
#   icon = "fa-brands fa-vimeo"
#   name = "Vimeo"
#   link = "https://vimeo.com"

# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
[params.contact]
  form_id = "your@email.com" # Add your form_id
  button_text = "Send now"

  # NOTE
  # Nomod comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = true
  disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
