baseURL = 'https://kcti111.github.io/magazine/'
languageCode = 'en-us'
title = '문화기술 이슈 매거진'
theme = "nomod"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
